package com.blandinf.androidtesttp.api

import com.blandinf.androidtesttp.models.User

class FakeApiService: ApiService {
    private val users = FakeApiServiceGenerator.FAKE_USERS
    /**
     * Return a list of [User]
     * Those users must be generated by [FakeApiServiceGenerator]
     */
    override fun getUsers(): List<User> {
        return users
    }

    /**
     * Generate a random [User] and add it [FakeApiService.users] list.
     * This user must be get from the [FakeApiServiceGenerator.FAKE_USERS_RANDOM] list.
     */
    override fun generateRandomUser() {
        users.add(0, FakeApiServiceGenerator.generateRandomUser())
    }

    /**
     * Delete a [User] from the [FakeApiService.users] list.
     */
    override fun deleteUser(user: User) {
        if (users.contains(user)) {
            users.remove(user)
        }
    }

    override fun clear() {
        users.clear()
    }
}